<?php $title='FreePlay Ingestion Test Report'; ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=htmlspecialchars($title)?></title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="css/app.css" rel="stylesheet"></head>
<body class="bg-body-tertiary"><nav class="navbar navbar-dark bg-dark"><div class="container-fluid"><a class="navbar-brand" href="index.php">← FreePlay</a><span id="testMode" class="badge text-bg-secondary">TEST MODE OFF</span></div></nav>
<main class="container-fluid py-3"><div class="d-flex flex-wrap justify-content-between gap-2 align-items-center"><div><h1 class="h3 mb-1">Ingestion Test Report</h1><div class="text-secondary">FPV1 camera-to-server validation</div></div><div><a href="api/test-export.php" class="btn btn-outline-secondary">Export JSON</a> <button id="refresh" class="btn btn-outline-primary">Refresh</button></div></div>
<section class="row g-3 my-1"><div class="col-md-4"><div class="card h-100"><div class="card-body"><div class="small text-secondary">OVERALL READINESS</div><div id="readiness" class="display-6">—</div><div id="recommendation" class="small"></div></div></div></div><div class="col-md-4"><div class="card h-100"><div class="card-body"><div class="small text-secondary">ACTIVE STREAMS</div><div id="activeStreams" class="display-6">0</div></div></div></div><div class="col-md-4"><div class="card h-100"><div class="card-body"><label class="form-label" for="streamId">Test target</label><div class="input-group"><input id="streamId" class="form-control" value="ring1_cam1"><input id="ring" type="number" class="form-control" value="1" min="1" max="14"></div></div></div></div></section>
<section><h2 class="h5 mt-4">Readiness gates</h2><div id="gates" class="row g-2"></div></section>
<section><h2 class="h5 mt-4">Active tests</h2><div id="activeTests" class="alert alert-secondary">No tests running.</div></section>
<section><div class="d-flex justify-content-between align-items-center mt-4"><h2 class="h5 mb-0">Tests and operator instructions</h2><div class="btn-group"><button class="btn btn-sm btn-primary suite" data-suite="quick">Quick Validation</button><button class="btn btn-sm btn-outline-primary suite" data-suite="single">Single Camera</button></div></div><div class="table-responsive mt-2"><table class="table table-hover align-middle"><thead><tr><th>Test</th><th>How to conduct the test</th><th>Category</th><th>Status</th><th>Last run</th><th>Action</th></tr></thead><tbody id="testRows"></tbody></table></div></section>
<section><h2 class="h5 mt-4">Historical runs</h2><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Run</th><th>Started</th><th>Status</th><th>Pass</th><th>Warn</th><th>Fail</th></tr></thead><tbody id="runRows"></tbody></table></div></section>
<div class="modal fade" id="detailModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h2 class="modal-title h5">Test details</h2><button class="btn-close" data-bs-dismiss="modal"></button></div><div id="detail" class="modal-body"></div></div></div></div></main>
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script><script src="js/tests.js"></script></body></html>
