'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {parseFpv1Binary,validateHello,sequenceDelta}=require('../protocol');
const {GopBuilder,GopReplayCache}=require('../gop');

function packet({pts=-12n,sequence=7,flags=1,tablet=999999999999n,payload=Buffer.from([1,2,3])}={}){const b=Buffer.alloc(32+payload.length);b.write('FPV1');b.writeBigInt64BE(pts,4);b.writeUInt32BE(sequence,12);b.writeUInt32BE(flags,16);b.writeUInt32BE(payload.length,20);b.writeBigUInt64BE(tablet,24);payload.copy(b,32);return b;}
test('parses strict, big-endian FPV1 packet without losing integers',()=>{const f=parseFpv1Binary(packet());assert.equal(f.ptsUs,-12n);assert.equal(f.tabletTimestampNs,999999999999n);assert.equal(f.sequence,7);assert.deepEqual(f.payload,Buffer.from([1,2,3]));});
test('rejects magic, short messages, and length mismatches',()=>{assert.throws(()=>parseFpv1Binary(Buffer.alloc(4)),/shorter/);const magic=packet();magic[0]=0;assert.throws(()=>parseFpv1Binary(magic),/magic/);const length=packet();length.writeUInt32BE(99,20);assert.throws(()=>parseFpv1Binary(length),/length/);});
test('validates complete hello',()=>{const input={type:'hello',protocol:'freeplay-ingest',version:1,streamId:'ring6_cam2',ring:6,camera:2,codec:'h264',width:1920,height:1080,fps:30,bitrate:6000000,keyframeInterval:1};const h=validateHello(input);assert.equal(h.ring,6);assert.throws(()=>validateHello({...input,protocol:'wrong'}),/protocol/);assert.throws(()=>validateHello({...input,version:2}),/version/);});
test('sequence arithmetic wraps at uint32',()=>{assert.equal(sequenceDelta(0xfffffffe,0xffffffff),1);assert.equal(sequenceDelta(0xffffffff,0),1);assert.equal(sequenceDelta(10,13),3);});
test('GOP builder waits for keyframe and finalizes at next keyframe',()=>{const b=new GopBuilder('ring1_cam1'),r={epochUs:100n,monotonicNs:1n};const f=(sequence,flags,pts)=>({sequence,flags,ptsUs:BigInt(pts),payloadLength:1,payload:Buffer.from([sequence]),tabletTimestampNs:1n});assert.equal(b.add(f(1,0,1),r,1).accepted,false);b.add(f(2,1,2),r,1);b.add(f(3,0,3),r,1);const x=b.add(f(4,1,4),r,1).finalized;assert.equal(x.encodedBufferCount,2);assert.equal(x.sequenceStart,2);});
test('replay cache is byte bounded and range queried',()=>{const c=new GopReplayCache(60,15);const g=n=>({startServerEpochUs:BigInt(n),endServerEpochUs:BigInt(n+1),byteLength:10});c.add(g(1));c.add(g(2));assert.equal(c.getStats().gops,1);assert.equal(c.query(0n,99n).length,1);});
