'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{EventEmitter}=require('events');
const WebSocket=require('ws');
const {CameraStreamCommandService,ControlError}=require('../stream-control');

function fixture(overrides={}){const sent=[];const socket={readyState:WebSocket.OPEN,send:value=>sent.push(JSON.parse(value))};const state={socket,streamId:'ring6_cam2',hello:{ring:6,camera:2,capabilities:{remoteStreamingControl:true,remoteStop:true}},streamState:'idle',streamGeneration:3,remoteControlEnabled:true,mediaReady:false};Object.assign(state,overrides);const liveStreams=new Map([[state.streamId,state]]);const audit=[];const service=new CameraStreamCommandService({liveStreams,events:new EventEmitter(),audit:x=>audit.push(x),config:{ackTimeoutMs:10000,startTimeoutMs:10000,stopTimeoutMs:10000,rateLimitMs:0,retentionMs:10000}});return {service,state,sent,audit};}

test('routes one start command and replays an idempotent IVR request',()=>{const f=fixture();const first=f.service.issue({ring:6,camera:2,desired:true,requestId:'request-1'});const replay=f.service.issue({ring:6,camera:2,desired:true,requestId:'request-1'});assert.equal(first.status,202);assert.equal(replay.command.commandId,first.command.commandId);assert.equal(f.sent.length,1);assert.deepEqual(f.sent[0].type,'set_streaming');assert.equal(f.sent[0].desired,true);clearTimeout(first.command.ackTimer);});
test('rejects unsupported, disabled, unknown, and conflicting requests',()=>{assert.throws(()=>fixture({hello:{ring:6,camera:2,capabilities:{}}}).service.issue({ring:6,camera:2,desired:true}),e=>e instanceof ControlError&&e.code==='remote_stream_control_unsupported');assert.throws(()=>fixture({remoteControlEnabled:false}).service.issue({ring:6,camera:2,desired:true}),e=>e.code==='remote_control_disabled');const f=fixture();assert.throws(()=>f.service.issue({ring:1,camera:1,desired:true}),e=>e.code==='camera_unknown');const c=f.service.issue({ring:6,camera:2,desired:true});assert.throws(()=>f.service.issue({ring:6,camera:2,desired:false}),e=>e.code==='camera_busy');clearTimeout(c.command.ackTimer);});
test('correlates acknowledgement and start completion to the issuing camera',()=>{const f=fixture(),issued=f.service.issue({ring:6,camera:2,desired:true});f.service.handle(f.state,{type:'command_ack',commandId:issued.command.commandId,accepted:true,streamState:'starting'});assert.equal(issued.command.acknowledgedAt>0,true);assert.equal(f.state.streamState,'starting');assert.equal(f.service.handle(f.state,{type:'stream_started',commandId:issued.command.commandId,streamGeneration:4}),true);assert.equal(f.state.streamState,'streaming');assert.equal(f.state.streamGeneration,4);assert.equal(f.state.activeCommandId,null);});
test('stop completion leaves the registered camera connected and idle',()=>{const f=fixture({streamState:'streaming',streamGeneration:4,mediaReady:true});const issued=f.service.issue({ring:6,camera:2,desired:false});f.service.handle(f.state,{type:'command_ack',commandId:issued.command.commandId,accepted:true,streamState:'stopping'});f.service.handle(f.state,{type:'stream_stopped',commandId:issued.command.commandId,streamGeneration:4});assert.equal(f.state.streamState,'idle');assert.equal(f.state.mediaReady,false);assert.equal(f.service.get('ring6_cam2').connected,true);});
test('commands for distinct cameras are independent',()=>{const f=fixture(),second={...f.state,streamId:'ring7_cam1',hello:{ring:7,camera:1,capabilities:{remoteStreamingControl:true,remoteStop:true}},socket:{readyState:WebSocket.OPEN,send:()=>{}},activeCommandId:null,lastCommandAt:null};f.service.liveStreams.set(second.streamId,second);const a=f.service.issue({ring:6,camera:2,desired:true}),b=f.service.issue({ring:7,camera:1,desired:true});assert.notEqual(a.command.commandId,b.command.commandId);clearTimeout(a.command.ackTimer);clearTimeout(b.command.ackTimer);});
test('disconnect is distinct from connected idle and cancels an active command',()=>{const f=fixture(),issued=f.service.issue({ring:6,camera:2,desired:true});f.service.disconnect(f.state);f.service.liveStreams.delete(f.state.streamId);const view=f.service.get(f.state.streamId);assert.equal(view.connected,false);assert.equal(view.streamState,'disconnected');assert.equal(issued.command.state,'cancelled_by_disconnect');assert.throws(()=>f.service.issue({ring:6,camera:2,desired:true}),e=>e.code==='camera_disconnected');});
test('duplicate acknowledgement and lifecycle completion are harmless',()=>{const f=fixture(),issued=f.service.issue({ring:6,camera:2,desired:true}),ack={type:'command_ack',commandId:issued.command.commandId,accepted:true,streamState:'starting'};f.service.handle(f.state,ack);f.service.handle(f.state,ack);const started={type:'stream_started',commandId:issued.command.commandId,streamGeneration:4};assert.equal(f.service.handle(f.state,started),true);assert.equal(f.service.handle(f.state,started),false);assert.equal(f.state.streamGeneration,4);});
test('acknowledgement timeout releases the per-camera command lock',async()=>{const f=fixture();f.service.config.ackTimeoutMs=5;const issued=f.service.issue({ring:6,camera:2,desired:true});await new Promise(resolve=>setTimeout(resolve,15));assert.equal(issued.command.state,'ack_timeout');assert.equal(f.state.activeCommandId,null);assert.equal(f.state.streamState,'error');});
