'use strict';
const protocolTests=require('./protocol-tests'),streamTests=require('./stream-tests'),timingTests=require('./timing-tests'),recordingTests=require('./recording-tests'),replayTests=require('./replay-tests'),resilienceTests=require('./resilience-tests'),loadTests=require('./load-tests');
const {calculateReadiness,gateSummary,result}=require('./test-utils');
const DEFINITIONS=[...protocolTests,...streamTests,...timingTests,...recordingTests,...replayTests,...resilienceTests,...loadTests];
const SUITES={quick:['protocol.fpv1-header','stream.codec-config','stream.gop-interval','stream.sequence','timing.pts'],single:['protocol.fpv1-header','stream.codec-config','stream.gop-interval','stream.sequence','timing.pts','recording.playable','recording.rotation','replay.random-access','replay.ram-cache'],ring:['stream.codec-config','stream.gop-interval','timing.pts','recording.playable','replay.random-access','replay.ram-cache','sync.three-camera'],resilience:['resilience.reconnect','backpressure.queue'],full:DEFINITIONS.filter(x=>x.id!=='load.capacity').map(x=>x.id),capacity:['load.capacity']};
function json(value){return JSON.stringify(value??null);} function parse(value,fallback){try{return value==null?fallback:JSON.parse(value);}catch(_){return fallback;}}
function createTestManager(deps){
 const {db,events}=deps,defs=new Map(DEFINITIONS.map(x=>[x.id,x])),active=new Map(),locks=new Map(),recent=[];
 const insertRun=db.prepare('INSERT INTO test_runs(name,started_at,status,config_snapshot_json,notes) VALUES (?,?,?,?,?)');
 const updateRun=db.prepare('UPDATE test_runs SET completed_at=?,status=? WHERE id=?');
 const insertResult=db.prepare('INSERT INTO test_results(test_run_id,test_id,category,name,description,status,severity,test_type,started_at,completed_at,duration_ms,expected_json,actual_json,metrics_json,observations_json,recommendation) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');
 function snapshot(){return {protocolVersion:1,serverVersion:1,maxRings:deps.config.maxRings,camerasPerRing:deps.config.camerasPerRing,ramReplaySeconds:deps.config.ramSeconds,fileRotationSeconds:deps.config.fileSeconds,videoDirectory:deps.videoDir,databasePath:deps.dbPath,baselineBitrate:6000000,baselineFps:30,testMode:deps.testMode};}
 function normalizeRow(r){return {...r,configSnapshot:parse(r.config_snapshot_json,{}),expected:parse(r.expected_json,{}),actual:parse(r.actual_json,{}),metrics:parse(r.metrics_json,{}),observations:parse(r.observations_json,[])};}
 function definitionView(d){return {id:d.id,category:d.category,name:d.name,description:d.description,severity:d.severity||'normal',testType:d.testType||'automatic',requiresTestMode:!!d.requiresTestMode,instructions:d.instructions||[],presets:d.presets||[]};}
 function lockNames(def,options){return typeof def.locks==='function'?def.locks(options):def.locks||[];}
 function acquire(def,options,key){for(const name of lockNames(def,options)){if(locks.has(name))throw Object.assign(new Error(`${name} is locked by ${locks.get(name)}`),{code:'test_conflict'});}for(const name of lockNames(def,options))locks.set(name,key);}
 function release(entry){for(const [name,key] of locks)if(key===entry.key)locks.delete(name);}
 function persist(runId,r){insertResult.run(runId,r.id,r.category,r.name,r.description,r.status,r.severity,r.testType,r.startedAt,r.completedAt,r.durationMs,json(r.expected),json(r.actual),json(r.metrics),json(r.observations),r.recommendation);}
 function complete(entry,r){if(entry.timer)clearTimeout(entry.timer);persist(entry.runId,r);updateRun.run(r.completedAt,r.status,entry.runId);release(entry);active.delete(entry.key);console.log(`FreePlay/Test completed ${r.id} ${r.status}`);return r;}
 function observationMatches(entry,e){return (!entry.options.streamId||entry.options.streamId===e.streamId)&&(!entry.options.ring||Number(entry.options.ring)===Number(e.ring));}
 events.on('test:observation',e=>{const item={...e,timeMs:e.timeMs||Date.now(),at:e.at||new Date().toISOString()};recent.push(item);if(recent.length>10000)recent.shift();for(const a of active.values())if(observationMatches(a,item)&&a.observations.length<10000)a.observations.push(item);});
 async function startTest(testId,options={}){const def=defs.get(testId);if(!def)throw Object.assign(new Error('Unknown testId'),{code:'unknown_test'});if(def.requiresTestMode&&!deps.testMode)throw Object.assign(new Error('This test requires FREEPLAY_TEST_MODE=1'),{code:'test_mode_required'});const key=`${testId}:${Date.now()}`;acquire(def,options,key);const startedAt=new Date().toISOString(),run=insertRun.run(def.name,startedAt,'RUNNING',json(snapshot()),String(options.notes||''));const entry={key,runId:Number(run.lastInsertRowid),def,options,startedAt,observations:[],actions:[],timer:null};active.set(key,entry);console.log(`FreePlay/Test started ${testId}`);try{if(def.run){const r=await def.run(deps,options);return {runId:entry.runId,result:complete(entry,{...r,startedAt,durationMs:Date.now()-Date.parse(startedAt)})};}const seconds=Number(options.durationSeconds||0);if(seconds>0)entry.timer=setTimeout(()=>{try{evaluateTest(testId);}catch(e){console.error('FreePlay/Test evaluate failed',e.message);}},seconds*1000);return {runId:entry.runId,result:result(def,{status:'RUNNING',startedAt,completedAt:startedAt}),instructions:def.instructions||[]};}catch(e){release(entry);active.delete(key);updateRun.run(new Date().toISOString(),'FAIL',entry.runId);throw e;}}
 function findActive(testId){return [...active.values()].find(x=>x.def.id===testId);}
 function evaluateTest(testId){const entry=findActive(testId);if(!entry)throw Object.assign(new Error('Test is not running'),{code:'not_running'});const r=entry.def.evaluate(deps,entry.options,entry.observations,entry.actions);r.startedAt=entry.startedAt;r.durationMs=Date.now()-Date.parse(entry.startedAt);return {runId:entry.runId,result:complete(entry,r)};}
 function stopTest(testId){const e=findActive(testId);if(!e)throw Object.assign(new Error('Test is not running'),{code:'not_running'});return {runId:e.runId,result:complete(e,result(e.def,{status:'SKIPPED',startedAt:e.startedAt,observations:['cancelled_by_operator'],recommendation:'Test was cancelled by the operator.'}))};}
 function action(testId,payload){const e=findActive(testId);if(!e)throw Object.assign(new Error('Test is not running'),{code:'not_running'});const allowed=['mark_event','set_sync_positions','note'];if(!allowed.includes(payload.action))throw Object.assign(new Error('Unsupported action'),{code:'invalid_action'});const a={...payload,at:new Date().toISOString(),serverTimeEpochUs:String(BigInt(Date.now())*1000n)};e.actions.push(a);console.log(`FreePlay/Test operator action ${testId} ${payload.action}`);return a;}
 async function startSuite(suiteId,options={}){const ids=SUITES[suiteId];if(!ids)throw Object.assign(new Error('Unknown suite'),{code:'unknown_suite'});const output=[];for(const id of ids){const def=defs.get(id);if(def.testType==='automatic')output.push(await startTest(id,options));}return {suiteId,started:output,operatorTests:ids.filter(id=>defs.get(id).testType!=='automatic')};}
 function listRuns(){return db.prepare(`SELECT tr.*,SUM(CASE WHEN rr.status='PASS' THEN 1 ELSE 0 END) pass_count,SUM(CASE WHEN rr.status='WARN' THEN 1 ELSE 0 END) warn_count,SUM(CASE WHEN rr.status='FAIL' THEN 1 ELSE 0 END) fail_count FROM test_runs tr LEFT JOIN test_results rr ON rr.test_run_id=tr.id GROUP BY tr.id ORDER BY tr.id DESC LIMIT 200`).all().map(normalizeRow);}
 function getRun(id){const run=db.prepare('SELECT * FROM test_runs WHERE id=?').get(id);if(!run)return null;return {...normalizeRow(run),results:db.prepare('SELECT * FROM test_results WHERE test_run_id=? ORDER BY id').all(id).map(normalizeRow)};}
 function allResults(){return db.prepare('SELECT * FROM test_results ORDER BY id').all().map(normalizeRow);}
 function statusView(){const results=allResults(),latest=[];for(const def of DEFINITIONS){const found=[...results].reverse().find(r=>r.test_id===def.id);latest.push(found?{...found,id:found.test_id}: {...definitionView(def),status:'NOT_RUN'});}return {testMode:deps.testMode,active:[...active.values()].map(e=>({runId:e.runId,testId:e.def.id,name:e.def.name,startedAt:e.startedAt,options:e.options,instructions:e.def.instructions||[],observations:e.observations.length})),tests:DEFINITIONS.map(definitionView),latestResults:latest,gates:gateSummary(latest),readiness:calculateReadiness(latest),runs:listRuns(),suites:Object.keys(SUITES),activeStreams:deps.liveStreams.size};}
 async function readBody(req){let text='';for await(const chunk of req){text+=chunk;if(text.length>1024*1024)throw Object.assign(new Error('Body too large'),{code:'invalid_request'});}if(!text)return {};try{return JSON.parse(text);}catch(_){throw Object.assign(new Error('Invalid JSON'),{code:'invalid_json'});}}
 async function handleHttp(req,res){
  const u=new URL(req.url,'http://localhost');if(!u.pathname.startsWith('/api/tests'))return false;res.setHeader('Content-Type','application/json');
  try {
   if(req.method==='GET'&&u.pathname==='/api/tests')res.end(json({ok:true,data:statusView()}));
   else if(req.method==='GET'&&u.pathname==='/api/tests/live')res.end(json({ok:true,data:statusView()}));
   else if(req.method==='GET'&&u.pathname==='/api/tests/export'){const view=statusView();res.setHeader('Content-Disposition','attachment; filename="freeplay-test-results.json"');res.end(json({serverVersion:1,protocolVersion:1,exportedAt:new Date().toISOString(),configuration:snapshot(),readiness:view.readiness,gates:view.gates,runs:view.runs,results:allResults()}));}
   else if(req.method==='GET'&&u.pathname==='/api/tests/runs')res.end(json({ok:true,data:{runs:listRuns()}}));
   else if(req.method==='GET'&&/^\/api\/tests\/runs\/\d+$/.test(u.pathname)){const r=getRun(Number(u.pathname.split('/').pop()));if(!r){res.statusCode=404;res.end(json({ok:false,error:{code:'not_found',message:'Run not found'}}));}else res.end(json({ok:true,data:r}));}
   else if(req.method==='POST'){const b=await readBody(req);let data;if(u.pathname==='/api/tests/run')data=b.suiteId?await startSuite(b.suiteId,b.options||b):await startTest(b.testId,b.options||b);else if(u.pathname==='/api/tests/stop')data=stopTest(b.testId);else if(u.pathname==='/api/tests/evaluate')data=evaluateTest(b.testId);else if(u.pathname==='/api/tests/action')data=action(b.testId,b);else throw Object.assign(new Error('Not found'),{code:'not_found'});res.end(json({ok:true,data}));}
   else{res.statusCode=404;res.end(json({ok:false,error:{code:'not_found',message:'Not found'}}));}
  }catch(e){res.statusCode=e.code==='test_conflict'?409:400;res.end(json({ok:false,error:{code:e.code||'test_error',message:e.message}}));}return true;
 }
 return {listTests:()=>DEFINITIONS.map(definitionView),listRuns,getRun,startTest,stopTest,evaluateTest,startSuite,getStatus:statusView,handleHttp,action};
}
module.exports={createTestManager,DEFINITIONS,SUITES};
