'use strict';
const STATUSES=new Set(['NOT_RUN','RUNNING','PASS','WARN','FAIL','SKIPPED']);
const THRESHOLDS=Object.freeze({gopTargetMs:1000,gopWarnMinMs:800,gopWarnMaxMs:1200,gopFailMaxMs:2000,syncPassMs:33.5,syncWarnMs:100,replayLookupWarnMs:250,replayLookupFailMs:1000,reconnectWarnMs:5000,reconnectFailMs:15000});
function stats(values){const a=values.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return {count:0,min:null,max:null,average:null,median:null,stddev:null};const average=a.reduce((x,y)=>x+y,0)/a.length;return {count:a.length,min:a[0],max:a[a.length-1],average,median:a.length%2?a[(a.length-1)/2]:(a[a.length/2-1]+a[a.length/2])/2,stddev:Math.sqrt(a.reduce((n,x)=>n+(x-average)**2,0)/a.length)};}
function status(value){if(!STATUSES.has(value))throw new Error(`Invalid test status: ${value}`);return value;}
function result(def,patch={}){const startedAt=patch.startedAt||new Date().toISOString(),completedAt=patch.completedAt||new Date().toISOString();return {id:def.id,category:def.category,name:def.name,description:def.description,status:status(patch.status||'PASS'),severity:def.severity||'normal',testType:def.testType||'automatic',startedAt,completedAt,durationMs:Math.max(0,patch.durationMs??(Date.parse(completedAt)-Date.parse(startedAt))),expected:patch.expected||{},actual:patch.actual||{},metrics:patch.metrics||{},observations:patch.observations||[],recommendation:patch.recommendation||null};}
const REQUIRED=['protocol.fpv1-header','stream.codec-config','stream.gop-interval','stream.sequence','timing.pts','recording.playable','replay.random-access','replay.ram-cache','resilience.reconnect','sync.three-camera'];
function calculateReadiness(results){const latest=new Map();for(const r of results)latest.set(r.id,r);const blocking=[],warnings=[],missing=[];for(const id of REQUIRED){const r=latest.get(id);if(!r||['NOT_RUN','RUNNING','SKIPPED'].includes(r.status))missing.push(id);else if(r.status==='FAIL')blocking.push({id,name:r.name,reason:r.recommendation||'Test failed'});else if(r.status==='WARN')warnings.push({id,name:r.name,reason:r.recommendation||'Warning requires acceptance'});}const readiness=blocking.length||missing.length?'NOT_READY':warnings.length?'WARN':'READY';return {readiness,blocking,warnings,missing,recommendation:readiness==='READY'?'READY FOR LAPTOP REPLAY PROTOCOL DESIGN':'NOT READY — complete or resolve the listed ingestion validation gates first'};}
function gateSummary(results){const groups={Protocol:['protocol.','stream.codec','stream.gop','stream.sequence','timing.'],Recording:['recording.'],Replay:['replay.'],Resilience:['resilience.','backpressure.'],Sync:['sync.'],Capacity:['endurance.','load.']};const rank={FAIL:5,WARN:4,RUNNING:3,PASS:2,SKIPPED:1,NOT_RUN:0};return Object.entries(groups).map(([name,prefixes])=>{const rs=results.filter(r=>prefixes.some(p=>r.id.startsWith(p)));let state='NOT_RUN';for(const r of rs)if(rank[r.status]>rank[state])state=r.status;return {name,status:state,tests:rs.length};});}
module.exports={THRESHOLDS,stats,result,calculateReadiness,gateSummary,status};
