'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{EventEmitter}=require('events');
const Database=require('better-sqlite3'),protocol=require('../protocol');
const {stats,calculateReadiness,gateSummary,THRESHOLDS}=require('./test-utils');
const {createTestManager}=require('./test-manager');

function manager(t){let db;try{db=new Database(':memory:');}catch(e){t.skip(`better-sqlite3 native binding unavailable: ${e.code||e.message}`);return null;}db.exec(`CREATE TABLE test_runs(id INTEGER PRIMARY KEY,name TEXT,started_at TEXT,completed_at TEXT,status TEXT,config_snapshot_json TEXT,notes TEXT);CREATE TABLE test_results(id INTEGER PRIMARY KEY,test_run_id INTEGER,test_id TEXT,category TEXT,name TEXT,description TEXT,status TEXT,severity TEXT,test_type TEXT,started_at TEXT,completed_at TEXT,duration_ms INTEGER,expected_json TEXT,actual_json TEXT,metrics_json TEXT,observations_json TEXT,recommendation TEXT);CREATE TABLE cameras(id INTEGER PRIMARY KEY,stream_id TEXT);CREATE TABLE files(id INTEGER PRIMARY KEY,camera_id INTEGER,path TEXT,complete INTEGER,started_at TEXT,ended_at TEXT);CREATE TABLE gop_index(id INTEGER PRIMARY KEY,camera_id INTEGER,start_time_epoch_us INTEGER,end_time_epoch_us INTEGER);`);const events=new EventEmitter();const deps={db,events,liveStreams:new Map(),protocol,config:{maxRings:14,camerasPerRing:3,ramSeconds:60,ramBytes:1000,fileSeconds:60},metrics:{protocolErrors:0},root:process.cwd(),dbPath:':memory:',videoDir:'/tmp',testMode:true};return {db,events,m:createTestManager(deps)};}
test('aggregate statistics are deterministic',()=>{assert.deepEqual(stats([3,1,2]),{count:3,min:1,max:3,average:2,median:2,stddev:Math.sqrt(2/3)});assert.equal(stats([]).count,0);});
test('readiness blocks missing required results and failed gates',()=>{const r=calculateReadiness([]);assert.equal(r.readiness,'NOT_READY');assert.ok(r.missing.includes('protocol.fpv1-header'));const gates=gateSummary([{id:'recording.playable',status:'FAIL'}]);assert.equal(gates.find(x=>x.name==='Recording').status,'FAIL');});
test('sync threshold boundaries are centralized',()=>{assert.equal(THRESHOLDS.syncPassMs,33.5);assert.equal(THRESHOLDS.syncWarnMs,100);});
test('automatic run persists its result',async t=>{const setup=manager(t);if(!setup)return;const {db,m}=setup;const out=await m.startTest('protocol.fpv1-header');assert.equal(out.result.status,'PASS');assert.equal(db.prepare('SELECT COUNT(*) n FROM test_runs').get().n,1);assert.equal(db.prepare('SELECT status FROM test_results').get().status,'PASS');db.close();});
test('resource locks reject conflicting stream tests and release on stop',async t=>{const setup=manager(t);if(!setup)return;const {db,m}=setup;await m.startTest('stream.codec-config',{streamId:'ring1_cam1'});await assert.rejects(m.startTest('stream.gop-interval',{streamId:'ring1_cam1'}),e=>e.code==='test_conflict');m.stopTest('stream.codec-config');await m.startTest('stream.gop-interval',{streamId:'ring1_cam1'});m.stopTest('stream.gop-interval');db.close();});
